### ISSUE TITLE
Timeout not respected when chaining calls

### ISSUE THREAD

**Issue by jakob-o** [jcabi/jcabi-http#160] opened 2017-04-25 14:38 UTC
Hi,

it looks like the timeouts are only respected if set directly before `fetch()` otherwise they get lost, e.g.
```
// OK
Response response = new ApacheRequest(path)
    .method("GET")
    .timeout(connect, read)
    .fetch();
// Timeouts not respected
Response response = new ApacheRequest(path)
    .timeout(connect, read)
    .method("GET")
    .fetch();
```

Regards

Jakob

**Comment by 0crat** [comment] 2017-04-25 14:38
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment] 2017-04-28 05:52
@jakob-o this is _absolutely_ not possible. But let me investigate :)

**Comment by yegor256** [comment] 2017-04-28 05:55
@jakob-o investigated. It's not possible. Can you please provide a unit test to prove that this really happens.

**Comment by jakob-o** [comment] 2017-04-28 10:39
@yegor256 See PR #165

**Comment by jakob-o** [comment] 2017-04-28 11:17
It seems, that neither connect nor read are passed to the constructors in a couple of methods, e.g.
```
        return new BaseRequest(
            this.wire,
            this.home,
            headers,
            this.mtd,
            this.content
        );
```
See:
https://github.com/jcabi/jcabi-http/blob/master/src/main/java/com/jcabi/http/request/BaseRequest.java#L200
https://github.com/jcabi/jcabi-http/blob/master/src/main/java/com/jcabi/http/request/BaseRequest.java#L219

**Comment by yegor256** [comment] 2017-04-30 09:25
@jakob-o looks like you're right! Many thanks for the PR. Please, fix your branch so that it passes static analysis checks and I will merge.

**Comment by ivanov-d** [comment] 2020-05-03 13:18
@yegor256 , the bug is still reproducible in the latest version, because fix for back() method from https://github.com/jcabi/jcabi-http/pull/149 was not approved. Shall I open another PR since original author gave up on it?

**Comment by yegor256** [comment] 2020-06-16 05:57
@jakob-o PR #149 was merged

**Comment by yegor256** [comment] 2020-06-16 08:09
@rultor release, tag is `0.17.3`

**Comment by yegor256** [comment] 2020-06-16 08:22
@rultor release, tag is `1.17.3`

**Comment by andreoss** [comment] 2020-07-08 01:14
@jakob-o Fixed in [1.17.3](https://github.com/jcabi/jcabi-http/releases/tag/1.17.3)

**Closed by andreoss** 2020-07-08 01:14 UTC

**Comment by 0crat** [comment] 2020-07-08 01:31
Job `gh:jcabi/jcabi-http#160` is not assigned, can't get performer
