### ISSUE TITLE
Caching based on Last-Modified timestamp

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-http#90] opened 2015-05-26 08:51 UTC
Similar to the existing but overly simple `CachingWire`, there ought to be another wire that implements caching based on the `Last-Modified` response header and `If-Modified-Since` request header.

**Comment by dmarkov** [comment] 2015-06-15 07:56
@yegor256 please dispatch this issue

**Comment by dmarkov** [comment] 2015-10-15 08:08
@pecko the issue is yours, please help

**Comment by dmarkov** [comment] 2015-12-01 09:15
@olegsimanov it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by olegsimanov** [comment] 2015-12-10 20:09
Looks like its not possible to set response status to 304 in case client uses "If-Modified-Since" header. I'm not able to create DefaultResponse outside of request package nor can I set status because it's immutable. This task requires to modify response headers to set/add "Last-Modified" header with time stamp. Should I break the immutability of the DefaultResponse class?

**Comment by dmarkov** [comment] 2015-12-16 10:15
@olegsimanov check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck. added -30 to your rating, now it is equal to [-240](http://www.netbout.com/b/35927?open=rating)

**Comment by dmarkov** [comment] 2016-01-06 11:31
@piddubnyi can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here; Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by piddubnyi** [comment] 2016-01-16 09:38
@cvrebert Fix merged now, please close the issue.

**Closed** 2016-01-16 09:39 UTC
Labels: 30 mins, @piddubnyi, bug, DEV, enhancement

**Comment by dmarkov** [comment] 2016-01-19 08:45
@piddubnyi Thank you, I have added **30 mins** to your account in payment/transaction "`75037159`", time consumed: 283 hours and 53 mins

+30 to your rating, your total score is [+15](http://www.netbout.com/b/35966?open=rating)

**Comment by dmarkov** [comment] 2016-01-19 10:43
@cvrebert these 2 puzzles were created in this ticket: `90-35dd830e`, `90-f5d7f05d`/#120
