### ISSUE TITLE
RequestBody.set should have an overload that works with InputStream.

### ISSUE THREAD

**Issue by antonini** [jcabi/jcabi-http#102] opened 2015-07-08 11:53 UTC
RequestBody.set should have an overload that works with InputStream.

To work with binary files using String should be avoid because it change the content. But at the same time, working with byte[] solves that problem but create a new one.
When you work with byte[] you load all the file in memory, so if you have multiple users uploading large files you can stop you server because all files will be in memory.

**Comment by dmarkov** [comment] 2015-07-13 08:55
@yegor256 please do something about this issue

**Comment by yegor256** [comment] 2015-07-13 17:25
@antonini it's a duplicate of #84

**Closed by yegor256** 2015-07-13 17:25 UTC
